baseURL = "http://andrewkemp.dev"
languageCode = "en-us"
title = "Andrew Kemp, a Javascript Engineer"
theme = "code-editor"

[params]
    author = "Andrew Kemp"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.