baseURL = "https://andrewkemp.dev"
languageCode = "en-us"
title = "Andrew Kemp, a Javascript Engineer"
theme = "code-editor"

[params]
    author = "Andrew Kemp"
    locale = "en-US"
    rootlink = "https://andrewkemp.dev"